# Setup
title:               Study Food
tagline:             'Study Food'
description:         'Study Food adalah situs web resep masakan Indonesia yang menyajikan resep sederhana dan mudah dipraktikkan. Dibuat dengan HTML, CSS, dan JavaScript sebagai proyek web statis, serta dihosting menggunakan GitHub Pages.'
url:                 
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Wildan Hidayat
  url:               https://studyfood.github.io
  email:             studyfoodid@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
